Repository move4mobile/krew-workspace, pull requests merged in 2022-04, with the labels that each got.

#918 build(deps): weekly dependabot updates
  apps/krew-website/astro.config.mjs
  package-lock.json
  package.json
Labels: dependencies

#937 feat(krew-website): deprecation fix
  apps/krew-website/src/components/Footer.astro
  apps/krew-website/src/components/Head.astro
Labels: bug, app: krew-website

#939 build(deps): migrate nx to 13.9.5
  package-lock.json
  package.json
Labels: dependencies

#963 fix: update Astro config file
  apps/krew-website/astro.config.mjs
  apps/krew-website/src/components/Head.astro
  apps/krew-website/tailwind.config.js
  package.json
Labels: app: krew-website

#956 build(deps): weekly dependabot updates
  apps/krew-website/astro.config.mjs
  apps/krew-website/src/components/Head.astro
  apps/krew-website/tailwind.config.js
  decorate-angular-cli.js
  migrations.json
  nx.json
  package-lock.json
  package.json
Labels: dependencies

#972 build(deps): weekly dependabot updates
  package-lock.json
  package.json
Labels: dependencies

#1008 build(deps): migratie nx to 14.x
  .github/dependabot.yml
  apps/krew-ui-angular/jest.config.ts
  apps/krew-ui-angular/project.json
  apps/krew-ui-angular/tsconfig.app.json
  apps/krew-ui-angular/tsconfig.editor.json
  apps/krew-ui-angular/tsconfig.spec.json
  apps/krew-ui-react/jest.config.ts
  apps/krew-ui-react/project.json
  apps/krew-ui-react/src/main.tsx
  apps/krew-ui-react/tsconfig.app.json
  apps/krew-ui-react/tsconfig.spec.json
  jest.config.ts
  jest.preset.ts
  libs/api-client/jest.config.ts
  libs/api-client/project.json
  libs/api-client/tsconfig.lib.json
  libs/api-client/tsconfig.spec.json
  libs/krew-angular/feature-shell/jest.config.ts
  libs/krew-angular/feature-shell/project.json
  libs/krew-angular/feature-shell/tsconfig.lib.json
  libs/krew-angular/feature-shell/tsconfig.spec.json
  libs/shared/environments/jest.config.ts
  libs/shared/environments/project.json
  libs/shared/environments/tsconfig.lib.json
  libs/shared/environments/tsconfig.spec.json
  package-lock.json
  package.json
Labels: dependencies
